quarkus:
    hibernate-orm:
        physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        database:
            generation: none
        log:
            sql: true
            bind-parameters: true
    datasource:
        db-kind: postgresql
        username: postgres
        password: postgres
        jdbc:
            url: jdbc:postgresql://localhost:25432/postgres
            max-size: 10
    security:
        deny-unannotated-endpoints: true
        jaxrs:
            default-roles-allowed: user

saas:
    iam:
        auth0:
            domain: domain
            issuer: issuer
            audience: audience
            clientId: clientId
            clientSecret: clientSecret