name: quality
on:
    workflow_dispatch:
jobs:
    qodana:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: 'Qodana Scan'
                uses: JetBrains/qodana-action@main
                env:
                    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
